# SQL  Banco `biblioteca`

### 1. Título e ano de publicação de todos os livros

In [ ]:

SELECT titulo, ano_publicacao
FROM livros
ORDER BY titulo;

                                     titulo  ano_publicacao
0                                      1984            1949
1                         A Hora da Estrela            1977
2                     A Paixao Segundo G.H.            1964
3                    A Revolucao dos Bichos            1945
4           Assassinato no Expresso Oriente            1934
5                                     Brida            1990
6                         Capitaes da Areia            1937
7                       Cem Anos de Solidao            1967
8                              Dom Casmurro            1899
9                       E Nao Sobrou Nenhum            1939
10                 Gabriela, Cravo e Canela            1958
11          Harry Potter e a Camara Secreta            1998
12         Harry Potter e a Pedra Filosofal            1997
13  Harry Potter e o Prisioneiro de Azkaban            1999
14                         Laços de Familia            1960
15          Memorias Postumas de Bras Cubas            1881
16                             O Alquimista            1988
17              O Amor nos Tempos do Colera            1985
18                             Onze Minutos            2003
19                            Quincas Borba            1891

### 2. Livros de Romance, do mais antigo para o mais novo

In [ ]:

SELECT titulo, ano_publicacao
FROM livros
WHERE genero = 'Romance'
ORDER BY ano_publicacao;

                            titulo  ano_publicacao
0  Memorias Postumas de Bras Cubas            1881
1                    Quincas Borba            1891
2                     Dom Casmurro            1899
3                Capitaes da Areia            1937
4         Gabriela, Cravo e Canela            1958
5            A Paixao Segundo G.H.            1964
6                A Hora da Estrela            1977
7      O Amor nos Tempos do Colera            1985

### 3. Membros mais novos da base (cadastrados a partir de 01/06/2023)

In [ ]:

SELECT nome, data_cadastro
FROM membros
WHERE data_cadastro >= '2023-06-01'
ORDER BY data_cadastro;

                    nome data_cadastro
0  Bruna Azevedo Correia    2023-06-14
1    Diego Fonseca Ramos    2023-07-02
2   Camila Ribeiro Souza    2023-07-19
3    Igor Salles Batista    2023-08-08
4  Tatiane Lopes Moreira    2023-08-25

### 4. Quantos livros estão fora da biblioteca agora

In [ ]:

SELECT COUNT(*) AS emprestimos_em_aberto
FROM emprestimos
WHERE data_devolucao_real IS NULL;

   emprestimos_em_aberto
0                      7

### 5. Título de cada livro junto com o nome do autor

In [ ]:

SELECT l.titulo, a.nome AS autor
FROM livros l
JOIN autores a ON a.id_autor = l.id_autor
ORDER BY l.titulo;

                                     titulo                   autor
0                                      1984           George Orwell
1                         A Hora da Estrela       Clarice Lispector
2                     A Paixao Segundo G.H.       Clarice Lispector
3                    A Revolucao dos Bichos           George Orwell
4           Assassinato no Expresso Oriente         Agatha Christie
5                                     Brida            Paulo Coelho
6                         Capitaes da Areia             Jorge Amado
7                       Cem Anos de Solidao  Gabriel Garcia Marquez
8                              Dom Casmurro        Machado de Assis
9                       E Nao Sobrou Nenhum         Agatha Christie
10                 Gabriela, Cravo e Canela             Jorge Amado
11          Harry Potter e a Camara Secreta            J.K. Rowling
12         Harry Potter e a Pedra Filosofal            J.K. Rowling
13  Harry Potter e o Prisioneiro de Azkaban            J.K. Rowling
14                         Laços de Familia       Clarice Lispector
15          Memorias Postumas de Bras Cubas        Machado de Assis
16                             O Alquimista            Paulo Coelho
17              O Amor nos Tempos do Colera  Gabriel Garcia Marquez
18                             Onze Minutos            Paulo Coelho
19                            Quincas Borba        Machado de Assis

### 6. Quantos livros cada autor tem no acervo

In [ ]:

SELECT a.nome, COUNT(l.id_livro) AS total_livros
FROM autores a
LEFT JOIN livros l ON l.id_autor = a.id_autor
GROUP BY a.nome
ORDER BY total_livros DESC;

                     nome  total_livros
0            Paulo Coelho             3
1            J.K. Rowling             3
2        Machado de Assis             3
3       Clarice Lispector             3
4  Gabriel Garcia Marquez             2
5           George Orwell             2
6             Jorge Amado             2
7         Agatha Christie             2

### 7. Gênero com mais títulos no acervo

In [ ]:

SELECT genero, COUNT(*) AS total
FROM livros
GROUP BY genero
ORDER BY total DESC
LIMIT 1;

    genero  total
0  Romance      8

### 8. Valor total do acervo, por gênero

In [ ]:

SELECT genero, SUM(preco) AS valor_total
FROM livros
GROUP BY genero
ORDER BY valor_total DESC;

              genero  valor_total
0            Romance        257.3
1           Fantasia        137.0
2             Ficcao        104.5
3           Policial         60.9
4    Realismo Magico         42.0
5  Ficcao Cientifica         39.9
6             Fabula         28.0
7             Contos         25.5

### 9. Empréstimos devolvidos com atraso

Compara duas datas da mesma linha: a prevista e a real. Só entra na contagem quem já devolveu de fato (`IS NOT NULL`) — quem ainda está com o livro não conta como atrasado nem em dia, porque ainda não sabemos.

In [ ]:

SELECT COUNT(*) AS emprestimos_atrasados
FROM emprestimos
WHERE data_devolucao_real IS NOT NULL
  AND data_devolucao_real > data_devolucao_prevista;

   emprestimos_atrasados
0                      7